name: super-linter

on: push

jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run super-linter
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
        with:
          run-linter: true
          run-linter-on-failure: false
          run-linter-on-success: true
          run-linter-on-pull-request: true
          run-linter-on-push: true
          run-linter-on-schedule: false
          run-linter-on-issue-comment: false